import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/app/utils/supabase/admin";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email, city, ref, consented } = body;

    if (!email || !consented) {
      return NextResponse.json(
        { success: false, error: "Email and consent are required." },
        { status: 400 }
      );
    }

    // Check if email already exists
    const { data: existingUser } = await supabaseAdmin
      .from("waitlist")
      .select("email, referral_code, queue_position")
      .eq("email", email.toLowerCase().trim())
      .single();

    if (existingUser) {
      return NextResponse.json({
        success: true,
        referralCode: existingUser.referral_code,
        queuePosition: existingUser.queue_position,
        alreadyRegistered: true,
      });
    }

    // Get client info
    const ipAddress =
      request.headers.get("x-forwarded-for") ||
      request.headers.get("x-real-ip") ||
      "unknown";
    const userAgent = request.headers.get("user-agent") || "unknown";

    // Insert new waitlist entry
    const { data: newEntry, error } = await supabaseAdmin
      .from("waitlist")
      .insert({
        email: email.toLowerCase().trim(),
        city: city || null,
        referred_by: ref || null,
        consented: true,
        ip_address: ipAddress,
        user_agent: userAgent,
        referral_code: "", // Will be generated by trigger
        queue_position: 0, // Will be set by trigger
      })
      .select("referral_code, queue_position")
      .single();

    if (error) {
      console.error("Supabase insert error:", error);
      return NextResponse.json(
        { success: false, error: "Failed to join waitlist. Please try again." },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      referralCode: newEntry.referral_code,
      queuePosition: newEntry.queue_position,
    });
  } catch (error) {
    console.error("Signup error:", error);
    return NextResponse.json(
      { success: false, error: "Service unavailable." },
      { status: 502 }
    );
  }
}
